const SUPABASE_URL="https://qmgykhnpzxuzjywlnahg.supabase.co";
const SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtZ3lraG5wenh1emp5d2xuYWhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTA4ODE2MjcsImV4cCI6MjEwNjQ1NzYyN30.JSSxUMGX6u3Wy2FRhySR5BjP9JYzFZA2SX4bnlgR-WA";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let result={variants:{},scripts:{}},active="Instagram";
function networks(){return $$('fieldset input:checked').map(x=>x.value)}
function data(){return{title:$('#title').value.trim(),brand:$('#brand').value.trim(),brief:$('#brief').value.trim(),audience:$('#audience').value.trim(),goal:$('#goal').value,tone:$('#tone').value,networks:networks()}}
function message(text,type="ok"){const el=$('#msg');el.className=type;el.textContent=text}
function renderTabs(){const tabs=$('#tabs');tabs.innerHTML="";networks().forEach(n=>{const b=document.createElement("button");b.textContent=n;b.className=n===active?"active":"";b.onclick=()=>{active=n;render()};tabs.appendChild(b)})}
function render(){renderTabs();$('#previewBrand').textContent=$('#brand').value||"Sua marca";$('#previewTitle').textContent=$('#title').value||"Sua próxima publicação começa aqui";$('#previewNetwork').textContent=active+" · Prévia";$('#previewText').textContent=result.variants?.[active]||"Preencha o briefing e clique em “Gerar com IA”.";const s=result.scripts?.TikTok;$('#scriptBox').classList.toggle("hidden",!(active==="TikTok"&&s));$('#scriptText').textContent=s||""}
async function call(body){const r=await fetch(SUPABASE_URL+"/functions/v1/divulga-ai",{method:"POST",headers:{"Content-Type":"application/json","apikey":SUPABASE_ANON_KEY,"Authorization":"Bearer "+SUPABASE_ANON_KEY},body:JSON.stringify(body)});let j={};try{j=await r.json()}catch{}if(!r.ok)throw new Error(j.error||"A IA não respondeu.");return j}
async function status(){try{const j=await call({action:"status"});const on=j.connected===true;$('#aiState').textContent=on?"Conectada e pronta":"Indisponível";$('#badge').textContent=on?"IA ativa":"IA offline";$('#dot').style.background=on?"#22c55e":"#ef4444";$('#generate').disabled=!on}catch{$('#aiState').textContent="Indisponível";$('#badge').textContent="IA offline";$('#dot').style.background="#ef4444";$('#generate').disabled=true}}
$('#generate').onclick=async()=>{const d=data();if(!d.title||!d.brand||!d.brief||!d.networks.length){message("Preencha campanha, marca, briefing e escolha pelo menos uma rede.","err");return}const b=$('#generate');b.disabled=true;b.textContent="Gerando…";try{result=await call(d);active=d.networks[0];render();message("Conteúdo gerado. Revise antes de publicar.")}catch(e){message(e.message||"Não foi possível gerar.","err")}finally{b.disabled=false;b.textContent="✦ Gerar com IA"}};
$('#example').onclick=()=>{$('#title').value="Semana de boas-vindas";$('#brand').value="Sua Academia";$('#audience').value="Pessoas da região que querem começar a treinar";$('#goal').value="Divulgar uma oferta";$('#tone').value="Próximo e amigável";$('#brief').value="Apresentar a academia e convidar as pessoas a conhecer o espaço. Primeira semana grátis para novos alunos. Agendamento pelo direct.";$$('fieldset input').forEach(x=>x.checked=["Instagram","Facebook","TikTok"].includes(x.value));active="Instagram";render();message("Exemplo preenchido. Edite como quiser.")};
$('#save').onclick=()=>{localStorage.setItem("divulga-draft",JSON.stringify(data()));message("Rascunho salvo neste dispositivo.")};
$('#copy').onclick=async()=>{const t=result.variants?.[active];if(t){await navigator.clipboard.writeText(t);message("Texto copiado.")}};
$$("input,textarea,select").forEach(el=>el.addEventListener("input",render));$$('fieldset input').forEach(el=>el.addEventListener("change",()=>{if(!networks().includes(active))active=networks()[0]||"Instagram";render()}));
try{const d=JSON.parse(localStorage.getItem("divulga-draft")||"null");if(d){$('#title').value=d.title||"";$('#brand').value=d.brand||"";$('#brief').value=d.brief||"";$('#audience').value=d.audience||"";$('#goal').value=d.goal||"Atrair clientes";$('#tone').value=d.tone||"Próximo e amigável";$$('fieldset input').forEach(x=>x.checked=(d.networks||[]).includes(x.value));active=(d.networks||[])[0]||"Instagram"}}catch{}
render();status();